temporarily bypass the t.compile runtime error
temporary disable the t.compile to bypass the runtime error:
/tmp/tmppps365h6/main.cpp:26:10: fatal error: 'Python.h' file not found

need to fix later

Signed-off-by: roger <roger.feng@intel.com>